### ISSUE TITLE
mod search site - wonky search

### ISSUE THREAD

**Issue by tmihor** [johanahlkvist/poe-timeless-jewel-multitool#10]
Searching for 'minion' will throw error instead of returning any mod because Levenshtein's distance function will find least distance by returning the empty mod from data\filt_nonfilt_passives.json

Not sure if said empty mod {"": ""} is supposed to be in there in the first place.

_get_candidates() def needs improving at the end of the day.

Observed behavior:
Search for 'minion' returns error because empty mod. Removing empty mod from json makes def find 'farshot' (no results).
Search for 'minion damage' returns 'moredamage' (no results).
Search for 'increased minion damage' returns ('increasedminiondamage', '80% increased Minion Damage', '1') which is Slum Lord.. or rather was? (no results).
Search for 'minion increased life' returns Minions Deal % increased Damage result.
Search for 'increased minion life' returns % Increased Maximum Life result.

**Comment by johanahlqvist** [comment]
Hey!

You are very correct in that ranking results according to the levenshtein distance is not the best method for the mod search job, rather it was a quick and dirty fix for something that should ideally be done similar to how poe.trade does their mod search, namely by presenting a list of the most similar mod names and do the selection of mods mostly client side. I guess this is one of the tasks that should be done in order to complete #4. 

Perhaps a better way to do the search, if the current setup is to be retained, would be to match the exact string the user inputs and choose the result that has the least number of additions required to turn the input into the result? I could do this when I get home, or if you want to do this, you're more than welcome to.
